[package]
name = "udpChat"
version = "1.0.0"
edition = "2021"
description = "Simple chat over the UDP/IP stack"
license = "MIT"
authors = ["itsgerliz"]

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
log = "0.4.25"
env_logger = "0.11.6"